create package ADMIN_PACKAGE is

-- 函数：注销管理员操作
FUNCTION DELETE_ADMIN
(
	V_NO IN NUMBER
)
RETURN  VARCHAR2;

-- 函数：注册管理员
FUNCTION INSERT_INTO_ADMIN 
(
  V_NO IN NUMBER, 
  V_NAME IN VARCHAR2,
  V_PASSWORD IN VARCHAR2,
  V_ANSWER IN VARCHAR2,
  V_TEL IN VARCHAR2
)
RETURN VARCHAR2;

-- 函数：修改管理员密码
FUNCTION UPDATE_ADMIN_PASSWORD
(
V_NO IN NUMBER,
V_ANSWER IN VARCHAR2,
V_NEW_PASSWORD VARCHAR2
)
RETURN VARCHAR2;

-- 函数：修改管理员的密钥
FUNCTION UPDATE_ADMIN_ANSWER
(
	V_NO IN NUMBER,
	V_PASSWORD IN VARCHAR2,
	V_NEW_ANSWER IN VARCHAR2
)
RETURN VARCHAR2;

-- 函数：修改用户的资料
FUNCTION UPDATE_ADMIN_DATA
(
	V_NO IN NUMBER, 
	V_NAME IN VARCHAR2,
	V_TEL IN VARCHAR2
)
RETURN VARCHAR2;

-- 存储过程：查询指定管理员的账号信息
PROCEDURE FIND_ADMIN_INFO
(
P_VO IN OUT ADMININF.ADMNO%TYPE,
P_NAME OUT ADMININF.ADMNAME%TYPE,
P_TEL OUT ADMININF.ADMTEL%TYPE
);

-- 函数：查询指定管理员的密码
FUNCTION FIND_PASSWORD_BY_ADMNO 
  (V_NO IN VARCHAR2)
RETURN VARCHAR2;


end ADMIN_PACKAGE;
/

