create package body AUTHOR_PACKAGE is

-- 计算每个作者写的图书的数量
  FUNCTION COUNT_AUTHOR_BOOK_NUMBER (V_NAME IN OUT VARCHAR2)
RETURN VARCHAR2
IS
  P_COUNT NUMBER;
  P_RESTEL VARCHAR2(50);
BEGIN
  SELECT COUNT(*) 
  INTO P_COUNT
  FROM BOOK_INFO 
  WHERE AUTNAME = V_NAME;
  
  IF P_COUNT = 0 THEN
    P_RESTEL := '这个作者没有写过书';
  ELSE
    P_RESTEL := V_NAME||'写了 '||TO_CHAR(P_COUNT)||' 本书';
  END IF;
  RETURN P_RESTEL;
END COUNT_AUTHOR_BOOK_NUMBER;

-- 通过作者名查询作者的信息
PROCEDURE FIND_AUTHOR_INFO (V_NAME IN OUT VARCHAR2, V_COUNTRY OUT VARCHAR2)
IS
BEGIN
	SELECT COUNTRY 
	INTO V_COUNTRY
	FROM AUTHOR
	WHERE AUTNAME = V_NAME;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		V_COUNTRY := '查无此人';
END FIND_AUTHOR_INFO;

-- 通过作者名找作者的编号
FUNCTION FIND_AUTNO_BY_AUTNAME(V_NAME IN OUT VARCHAR2) 
RETURN NUMBER
IS
	P_AUTNO NUMBER;
BEGIN
	SELECT AUTNO 
	INTO P_AUTNO
	FROM AUTHOR
	WHERE AUTNAME = V_NAME;
	RETURN P_AUTNO;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		RETURN -1;
END FIND_AUTNO_BY_AUTNAME;

-- 向作者表中插入作者编号
PROCEDURE INSERT_INTO_AUTHOR (V_NAME IN VARCHAR2, V_COUNTRY IN VARCHAR2)
IS
	P_COUNT NUMBER;
BEGIN
	SELECT COUNT(*)
	INTO P_COUNT
	FROM AUTHOR
	WHERE AUTNAME = V_NAME;
	
	IF P_COUNT = 0 THEN
		INSERT INTO AUTHOR(AUTNAME,COUNTRY) VALUES(V_NAME,V_COUNTRY);
	END IF;
END INSERT_INTO_AUTHOR;

end AUTHOR_PACKAGE;
/

