create PROCEDURE FIND_STU_INFO(
P_STUNO IN STUDENT.STUNO%TYPE, 

P_STUNAME out STUDENT.STUNAME%TYPE,
P_SEX out STUDENT.SEX%TYPE,
P_AGE out STUDENT.AGE%TYPE,
P_CLASSNAME out STUDENT.CLASSNAME%TYPE,
P_STUTEL out STUDENT.STUTEL%TYPE
) 
IS
begin
  SELECT STUNAME,SEX,AGE,CLASSNAME,STUTEL
  INTO P_STUNAME,P_SEX,P_AGE,P_CLASSNAME,P_STUTEL
  FROM STUDENT
  WHERE STUNO = P_STUNO;
exception
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('查无此人');
end FIND_STU_INFO;
/

